name: Website CI-CD

on:
  push:
    branches: [main]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE: Dockerfile
      TAG: interwebsite
    steps:
     - uses: actions/checkout@v2  
     - name: Docker Login
       uses: docker/login-action@v3.0.0
       with:
        registry: ${{secrets.DOCKER_HOST}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}      
     - name: Build and push Docker images
  # You may pin to the exact commit or the version.
  # uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f5
       uses: docker/build-push-action@v5.1.0
       with:
        context: ./
        file: Dockerfile
        push: true
        tags: |
          ${{secrets.DOCKER_HOST}}/${{env.TAG}}
  deploy:
    needs: build-publish
    runs-on: cloud
    env:
      TAG: interwebsite
    steps:
     - name: Docker Login
       uses: docker/login-action@v3.0.0
       with:
        registry: ${{secrets.DOCKER_HOST}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}      
     - name: deploy
    # uses: nekiro/ssh-job@e0d177751aced5bcaf110ce4d782a681e5e12856
       run: docker pull ${{secrets.DOCKER_HOST}}/${{env.TAG}}; docker stop ${{env.TAG}}; docker rm ${{env.TAG}}; docker run --name ${{env.TAG}} --restart=unless-stopped -m=250m  -e 80:8109 -d ${{secrets.DOCKER_HOST}}/${{env.TAG}}; 
